Update project.py, Fix Type Error
`Exception in thread Thread-8 ():
Traceback (most recent call last):
File "C:\Users\ahmet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
self.run()
File "C:\Users\ahmet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\ahmet\OneDrive\Masaüstü\ddevi1\devika\devika.py", line 93, in
thread = Thread(target=lambda: agent.subsequent_execute(message, project_name))
File "C:\Users\ahmet\OneDrive\Masaüstü\ddevi1\devika\src\agents\agent.py", line 189, in subsequent_execute
conversation = self.project_manager.get_all_messages_formatted(project_name)
File "C:\Users\ahmet\OneDrive\Masaüstü\ddevi1\devika\src\project.py", line 123, in get_all_messages_formatted
if message["from_devika"]:
TypeError: string indices must be integers`
solves the problem that caused the error