Update researcher.py for TypeError: unsupported operand type(s) for |: 'type' and 'type'
TypeError: unsupported operand type(s) for |: 'type' and 'type' fix

We had to use Union instead of | which was causing an error